### PR TITLE
added todo app

### PR DESCRIPTION
**Pull request by ShudhanshuSingh**
## Resolves Issue #6 Todo list App

Delete a todo option
Checkbox for marking as completed and strikethrough over todo
whenever browser is refreshed the added todo list items shouldn't vanish.
>

### CODE REVIEW

**Comment by muddhit** [comment]
Add a hosted link and working scrnshot

**Comment by ShudhanshuSingh** [comment]
> Add a hosted link and working scrnshot

Okay I will give that by evening

**Comment by muddhit** [comment]
Sure

**Comment by ShudhanshuSingh** [comment]
> Sure

https://pensive-pare-fbd3d5.netlify.app
image

**Pull request merged**
